In [1]:
from RL_GoBot import var
from RL_GoBot.model import GoBot
from RL_GoBot.data_base import GoDatabase
from RL_GoBot.game_creation import self_play_MCTS

In [2]:
net = GoBot()
net.load_model("episode_2.pth")

db = GoDatabase(collection_name = "episode_2")    # collection_name will be different for each of the episodes of the bot learning

In [ ]:
games_move = self_play_MCTS(100, net, db)

new root 
 ___ node info ___
action : None | depth : 0
N : 0, P : 1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
 
 


C:\Users\matgi\OneDrive\Documents\ecole_lycee\AGH_Cracovie\cours\Machine_learning\projet_final\src\RL_GoBot\model.py:50: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:256.)
  x = torch.tensor(x, dtype=torch.float32)


policy :  tensor([[0.0000, 0.0392, 0.0506, 0.0392, 0.0226, 0.0226, 0.0000],
        [0.0000, 0.0226, 0.0226, 0.0000, 0.0847, 0.0320, 0.0000],
        [0.0320, 0.0226, 0.0000, 0.0226, 0.0000, 0.0226, 0.0226],
        [0.0226, 0.0226, 0.0226, 0.0226, 0.0226, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0226, 0.0751, 0.0226, 0.0226, 0.0000],
        [0.0000, 0.0784, 0.0000, 0.0000, 0.0933, 0.0226, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0226, 0.0000, 0.0226, 0.0226]])
pass :  0.022637706571627347
r :  0.5096809453141187
action :  23

 17.495867252349854
new root 
 ___ node info ___
action : (3, 2) | depth : 1
N : 1, P : OutputFormating(0.0199)
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
 
 
policy :  tensor([[0.0000, 0.0659, 0.0220, 0.0761, 0.0220, 0.0311, 0.0000],
        [0.0000, 0.0220, 0.0220, 0.0000, 0.0932, 0.0220, 0.0000],
        [0.0220, 0.0220, 0.0000, 