In [1]:
from gym_go.envs import go_env
from gym_go import gogame
import torch


In [ ]:
from RL_GoBot import var
from RL_GoBot.model import GoBot
from RL_GoBot.learning import get_optimizer, compute_loss, test, train
from RL_GoBot.MCTSearch import roll_policy, action2d, MCTS
from RL_GoBot.game_creation import sample_one_self_play_MCTS
from RL_GoBot.data_base import GoDatabase

7


In [3]:
env = go_env.GoEnv(size=var.BOARD_SIZE, komi=var.KOMI)
state, reward, done, info = env.step((0,0))
print(state[:4], '\n----\n')
state, reward, done, info = env.step((1,0))
print(state[:4])


[[[1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]] 
----

[[[1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0.

In [4]:
net = GoBot()
out = net.forward(state)
print(out.result[0])
print(out.result[0,10])



OutputFormating([-0.0137, -0.0428, -0.0987,  0.0936,  0.0153, -0.0621, -0.0969,
                  0.0312, -0.0182,  0.0511, -0.0637,  0.0385, -0.1041,  0.0482,
                  0.0071,  0.0310, -0.0186,  0.0312,  0.1193,  0.0860,  0.0295,
                  0.0931, -0.0677,  0.0439, -0.1022,  0.0777, -0.0875,  0.0698,
                 -0.0257, -0.0850, -0.0270,  0.0267,  0.0407, -0.1131,  0.0247,
                  0.0211,  0.0214,  0.0846,  0.1136,  0.0241, -0.0348,  0.0882,
                  0.0414, -0.0367,  0.1028,  0.0748,  0.0384, -0.0290,  0.0923,
                  0.0547], grad_fn=<AliasBackward0>)
OutputFormating(-0.0637, grad_fn=<AliasBackward0>)


In [5]:
state = gogame.init_state(var.BOARD_SIZE)
print(roll_policy(state, net))

C:\Users\matgi\OneDrive\Documents\ecole_lycee\AGH_Cracovie\cours\Machine_learning\projet_final\src\RL_GoBot\model.py:49: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:256.)
  x = torch.tensor(x, dtype=torch.float32)


-1.0


In [ ]:
net = GoBot()
net.load_model("first.pth")

In [7]:
state = gogame.init_state(var.BOARD_SIZE)
root = MCTS(state, None, 1)
MCTS.net = net
for i in range(var.N_THRESHOLD + 3) :
    root.push_search()


extende :  None 0


In [8]:
game_1 = sample_one_self_play_MCTS(net)

root ___ node info ___
action : None | depth : 0
0
 
extende :  None 0
extende :  (4, 3) 1
extende :  (6, 5) 1
extende :  (0, 3) 1
extende :  (5, 0) 1

 7.573477268218994
root ___ node info ___
action : (5, 0) | depth : 1
14
 
extende :  (4, 2) 2
extende :  (6, 5) 2
extende :  (0, 3) 2
extende :  (1, 1) 2
extende :  (4, 6) 2

 5.5449676513671875
root ___ node info ___
action : (4, 2) | depth : 2
14
 
extende :  (2, 4) 3
extende :  (4, 3) 3
extende :  (6, 5) 3
extende :  (3, 4) 3
extende :  (0, 3) 3
extende :  (0, 0) 3

 6.0972514152526855
root ___ node info ___
action : (4, 3) | depth : 3
17
 
extende :  (0, 3) 4
extende :  (0, 0) 4
extende :  (1, 1) 4
extende :  (4, 6) 4
extende :  (4, 5) 4

 5.267083406448364
root ___ node info ___
action : (4, 6) | depth : 4
15
 
extende :  (3, 4) 5
extende :  (0, 0) 5
extende :  (4, 4) 5
extende :  (2, 1) 5

 8.571965217590332
root ___ node info ___
action : (0, 0) | depth : 5
22
 
extende :  (0, 3) 6
extende :  (5, 6) 6
extende :  (2, 1) 6
extende

KeyboardInterrupt: 

In [ ]:
print(game_1)

[[array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
    

In [ ]:
db = GoDatabase()

db.save_one_game(episode = 0, game = game_1)