In [1]:
from gym_go.envs import go_env
from gym_go import gogame
# import torch


In [2]:
from RL_GoBot import var
from RL_GoBot.model import GoBot
from RL_GoBot.learning import get_optimizer, compute_loss, test, train
from RL_GoBot.MCTSearch import roll_policy, action2d, MCTS
from RL_GoBot.game_creation import sample_one_self_play_MCTS
from RL_GoBot.data_base import GoDatabase

7


In [4]:
env = go_env.GoEnv(size=var.BOARD_SIZE, komi=var.KOMI)
state, reward, done, info = env.step((0,0))
print(state[:4], '\n----\n')
state, reward, done, info = env.step((1,0))
print(state[:4])


[[[1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]] 
----

[[[1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0.

In [5]:
net = GoBot()
out = net.forward(state)
print(out.result[0])
print(out.result[0,10])



OutputFormating([ 0.0286, -0.1007, -0.0531, -0.1142,  0.0825, -0.0759,  0.0030,
                 -0.0726, -0.0145, -0.0030,  0.0827,  0.0402,  0.0287,  0.0722,
                  0.0129,  0.0629, -0.0327, -0.0950, -0.0631, -0.0235,  0.0749,
                 -0.0473,  0.0331,  0.0415, -0.0055,  0.0193, -0.0213, -0.0281,
                 -0.0135, -0.0629,  0.0827,  0.0808,  0.1023,  0.0545,  0.0581,
                  0.0243,  0.0170, -0.0304,  0.0128,  0.0249,  0.0843, -0.0016,
                  0.0569, -0.1083, -0.0274, -0.0348, -0.0269,  0.0523, -0.0078,
                  0.0402], grad_fn=<AliasBackward0>)
OutputFormating(0.0827, grad_fn=<AliasBackward0>)


In [6]:
state = gogame.init_state(var.BOARD_SIZE)
print(roll_policy(state, net))

C:\Users\matgi\OneDrive\Documents\ecole_lycee\AGH_Cracovie\cours\Machine_learning\projet_final\src\RL_GoBot\model.py:51: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:256.)
  x = torch.tensor(x, dtype=torch.float32)


-1.0


In [7]:
net = GoBot()
net.load_model("test.pth")

In [8]:
state = gogame.init_state(var.BOARD_SIZE)
root = MCTS(state, None, 1)
MCTS.net = net
for i in range(var.N_THRESHOLD + 3) :
    root.push_search()


extende :  None 0


In [9]:
game_1 = sample_one_self_play_MCTS(net)

___ node info ___
action : None | depth : 0
0
 
extende :  None 0
extende :  (4, 0) 1
in next_node()

 10.631982326507568
___ node info ___
action : (1, 1) | depth : 1
5
 
extende :  (1, 1) 1
extende :  (4, 0) 2


KeyboardInterrupt: 

In [ ]:
print(game_1)

NameError: name 'game_1' is not defined

In [ ]:
db = GoDatabase(collection_name = "test")

db.save_one_game(episode = 0, game = game_1)